version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
